server:
  port: ${PORT:8761}
spring:
    application:
        name: server-discovery
eureka:
    client:
      register-with-eureka: false
      fetch-registry: false
      service-url:
        defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka/}